/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MyFlowsRouteImport } from './routes/my-flows'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as EnvRouteImport } from './routes/env'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DevApiRouteImport } from './routes/dev-api'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIdRouteImport } from './routes/s.$id'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFlowsRoute = MyFlowsRouteImport.update({
  id: '/my-flows',
  path: '/my-flows',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvRoute = EnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevApiRoute = DevApiRouteImport.update({
  id: '/dev-api',
  path: '/dev-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-api': typeof DevApiRoute
  '/docs': typeof DocsRoute
  '/domains': typeof DomainsRoute
  '/env': typeof EnvRoute
  '/flows': typeof FlowsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-flows': typeof MyFlowsRoute
  '/payments': typeof PaymentsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/surveys': typeof SurveysRoute
  '/templates': typeof TemplatesRoute
  '/tickets': typeof TicketsRoute
  '/voice': typeof VoiceRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-api': typeof DevApiRoute
  '/docs': typeof DocsRoute
  '/domains': typeof DomainsRoute
  '/env': typeof EnvRoute
  '/flows': typeof FlowsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-flows': typeof MyFlowsRoute
  '/payments': typeof PaymentsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/surveys': typeof SurveysRoute
  '/templates': typeof TemplatesRoute
  '/tickets': typeof TicketsRoute
  '/voice': typeof VoiceRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-keys': typeof ApiKeysRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-api': typeof DevApiRoute
  '/docs': typeof DocsRoute
  '/domains': typeof DomainsRoute
  '/env': typeof EnvRoute
  '/flows': typeof FlowsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-flows': typeof MyFlowsRoute
  '/payments': typeof PaymentsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/surveys': typeof SurveysRoute
  '/templates': typeof TemplatesRoute
  '/tickets': typeof TicketsRoute
  '/voice': typeof VoiceRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-keys'
    | '/automations'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/dev-api'
    | '/docs'
    | '/domains'
    | '/env'
    | '/flows'
    | '/integrations'
    | '/login'
    | '/messages'
    | '/my-flows'
    | '/payments'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/surveys'
    | '/templates'
    | '/tickets'
    | '/voice'
    | '/s/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-keys'
    | '/automations'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/dev-api'
    | '/docs'
    | '/domains'
    | '/env'
    | '/flows'
    | '/integrations'
    | '/login'
    | '/messages'
    | '/my-flows'
    | '/payments'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/surveys'
    | '/templates'
    | '/tickets'
    | '/voice'
    | '/s/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-keys'
    | '/automations'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/dev-api'
    | '/docs'
    | '/domains'
    | '/env'
    | '/flows'
    | '/integrations'
    | '/login'
    | '/messages'
    | '/my-flows'
    | '/payments'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/surveys'
    | '/templates'
    | '/tickets'
    | '/voice'
    | '/s/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AutomationsRoute: typeof AutomationsRoute
  CampaignsRoute: typeof CampaignsRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  DevApiRoute: typeof DevApiRoute
  DocsRoute: typeof DocsRoute
  DomainsRoute: typeof DomainsRoute
  EnvRoute: typeof EnvRoute
  FlowsRoute: typeof FlowsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MyFlowsRoute: typeof MyFlowsRoute
  PaymentsRoute: typeof PaymentsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SurveysRoute: typeof SurveysRoute
  TemplatesRoute: typeof TemplatesRoute
  TicketsRoute: typeof TicketsRoute
  VoiceRoute: typeof VoiceRoute
  SIdRoute: typeof SIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-flows': {
      id: '/my-flows'
      path: '/my-flows'
      fullPath: '/my-flows'
      preLoaderRoute: typeof MyFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env': {
      id: '/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof EnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-api': {
      id: '/dev-api'
      path: '/dev-api'
      fullPath: '/dev-api'
      preLoaderRoute: typeof DevApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiKeysRoute: ApiKeysRoute,
  AutomationsRoute: AutomationsRoute,
  CampaignsRoute: CampaignsRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  DevApiRoute: DevApiRoute,
  DocsRoute: DocsRoute,
  DomainsRoute: DomainsRoute,
  EnvRoute: EnvRoute,
  FlowsRoute: FlowsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MyFlowsRoute: MyFlowsRoute,
  PaymentsRoute: PaymentsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SurveysRoute: SurveysRoute,
  TemplatesRoute: TemplatesRoute,
  TicketsRoute: TicketsRoute,
  VoiceRoute: VoiceRoute,
  SIdRoute: SIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
